kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claimr
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: test2

