apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
spec:
  replicas: 1
  serviceName: jenkins  
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts
        imagePullPolicy: Always
        name: container-0
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 0
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-vol 
  volumeClaimTemplates:
    - metadata:
          name: jenkins-vol
      spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "gp2"  
          resources:
           requests:
             storage: 10Gi       
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins

