
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: data-elasticsearch-master-0
spec:
    storageClassName: ssd-storage
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: pvc-63f740df-f102-4f3f-a103-9a97eb6afe5b
                                        