
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: data-elasticsearch-data-0
spec:
    storageClassName: ssd-storage
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 22Gi
    volumeName: pvc-8a2fc3e4-17fe-4c75-9f69-3e01071ad439
                                        