
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: data-elasticsearch-master-2
spec:
    storageClassName: ssd-storage
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: pvc-8b4e369e-b8f6-46cb-9292-91375fc0ab5b
                                        