
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: data-elasticsearch-data-2
spec:
    storageClassName: ssd-storage
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    volumeName: pvc-611ae391-2651-4156-92c5-ba49cccf9974
                                        