
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: data-elasticsearch-master-1
spec:
    storageClassName: ssd-storage
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: pvc-d73a4065-2217-41bf-8d1c-b17cc28249cb
                                        