
kind: PersistentVolume
apiVersion: v1
metadata:
    name: pvc-63f740df-f102-4f3f-a103-9a97eb6afe5b
    namespace: es-sandboxppfa
    labels:
        type: amazonEBS
spec:
    capacity:
      storage: 10Gi
    storageClassName: ssd-storage
    accessModes:
    - ReadWriteOnce
    nodeAffinity:
     required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1b
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-east-1

    awsElasticBlockStore:
      volumeID: vol-042a345f99c6ed9e0
      fsType: ext4
                                        