
kind: PersistentVolume
apiVersion: v1
metadata:
    name: pvc-5a695084-b4a6-4a7b-8e5e-458d2ac7b3d3
    namespace: es-sandboxclient
    labels:
        type: amazonEBS
spec:
    capacity:
      storage: 20Gi
    storageClassName: ssd-storage
    accessModes:
    - ReadWriteOnce
    nodeAffinity:
     required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1a
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-east-1

    awsElasticBlockStore:
      volsfweumeID: volsfwe-0984c49e73a58d3dd
      fsType: ext4
                                        